# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 02:37
from __future__ import unicode_literals

import apps.travelbuddy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_auto_20171021_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='plan',
        ),
        migrations.AddField(
            model_name='trip',
            name='plans',
            field=models.CharField(default='fun', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=45, validators=[apps.travelbuddy.models.nameMinLength]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[apps.travelbuddy.models.pwMinLength]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, validators=[apps.travelbuddy.models.nameMinLength]),
        ),
    ]
